version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
    depends_on:
      - app
    networks:
      - lesson_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - lesson_net

networks:
  lesson_net:
    driver: bridge